<a href="https://colab.research.google.com/github/LamuneGitHub/A001_Python_Test/blob/main/EDA_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

----
----
# # EDA ( Exploratory Data Analysis )( 탐색적 데이터 분석)
## 정의
> : 탐색적 데이터 분석  
: 데이터의 특징을 파악하는것

## 목적
> : 본격적인 데이터 분석이나 모델링 전에 데이터의 특징을 파악하여 분석 계획을 세우기 위한 기초공사 작업  
  : 유의미한 business insight(업무 통찰)을 얻기 위함  
  : 시행착오 비용 최소화

## 수행 과정 및 방법
* Data Description 확인 (데이터 명세서 )  
  : 데이터 명세서를 읽어서 데이터의 특성을 이해 

* 시각적 분석
  * 엑셀등을 이용하여 직접 눈으로 특성을 분석

* 프로그램적 분석
  * 분석 메소드 활용
    * info()
    * shape
    * description()
    * isnull().sum()
    * duplicated()
    * 기타 프로그램코딩 활용
  * Feature Engineering 
  * 시각화

> 목표 (프로그램적 분석의)
  * 결측치 확인
    * 컬럼별 결측치 비율
  * 카테고리 값의 비율
  * 가능 범위를 벗어난 값 확인
  * 계산값이 틀린 값 확인
  * 이상한 문자가 들어간 값 확인
  * 중복값

* Feature Engineering (변수 가공)
* Business Insight (업무 통찰)

# # 프로그램 기본 설정

In [3]:
# import

%matplotlib inline

from IPython.display import display

import re
import math
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import random

import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

from scipy import stats
from scipy.stats import ttest_1samp, ttest_ind



#pandas에서 DataFrame을 요약해서 표시하지 않도록 설정
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# head로 표시할 데이터 갯수 
print_row_count = 3

In [ ]:
# # 구글 드라이브 mount
# from google.colab import drive
# drive.mount('/content/drive');

# # 함수 정의

In [4]:
# 줄 구분 표시 출력 
def print_line() :
  print ("\n------------------------------------------------")
def print_line_m() :
  print ("\n-----------------------")
def print_line_s() :
  print ("\n----------")

In [ ]:
def 간단EDA_확인() :
    
    print( "컬럼별 결측치 갯수(전체)" , df.isnull().sum() )
    
    print( "중복 data 갯수(전체)" , df.duplicated(keep = False).sum() )
    print( "중복 data " , df[df.duplicated(keep = False)].head(10) )
    print( f" id 컬럼의 중복 갯수{ df['id'].duplicated(keep = False).sum() } " )

In [10]:
# 결측치가 포함된 df를 반환 한다. ( copy 된 data)
"""
    str_replace = np.nan # 결측치를 변경할 문자
    ,need_replace = False # 결측치 변경이 필요한지 여부 
    ,need_drop = False # 결측치 행의 삭제가 필요한지 여부
"""
def 결측치행열조회( df_target , str_replace = np.nan , need_replace = False , need_drop = False) :

    # 결측치로 인식할 문자열
    #str_replace = '-' # 결측치를 변경할 문자
    lst_na_str = [ np.NaN , '-' , "N/A" 'NA' , 'na', 'NaN' , "" ]   # 결측치로 인식할 문자들 

    # 조회
    cond_tmp1 = df_target.isin(lst_na_str).any( axis= 1)

    # isnull()의 결과는 위에 포함 되므로 반복 처리 해 주지 않아도 된다. 
    """
    # 빈값 조회
    cond_tmp2 = df_target.isnull().any(axis= 1)

    # 빈값 이거나, 빈값 문자열인 경우
    cond_tmp3 = cond_tmp1 | cond_tmp2

    set_1 = set(trueIndex리스트반환( cond_tmp1 ))
    set_2 = set(trueIndex리스트반환( cond_tmp2 ))

    print ( set_1 > set_2 )
    print ( set_1 == set_2 )
    print ( set_1 < set_2 )"""

    # 결측치가 포함된 컬럼명 조회
    sri_tmp = df_target.isin(lst_na_str).any()
    list_col = sri_tmp[sri_tmp == True].index

    # 작업 Df 생성
    df_tmp = df_target[cond_tmp1][list_col].copy()
    #display ( df_tmp  )
    #display ( df_target[cond_tmp1][list_col]  )

    # 출력
    print ( f"결측치가 포함된 Data 갯수 {len(df_tmp)} / { len(df_target)} " )
    print ( f"각 컬럼별 결측치 갯수")
    print ( f"{df_tmp.isin(lst_na_str).sum()}")

    # (TODO)결측치로 인식한 문자열을  str_replace 으로 변경
    if need_replace :
        df_tmp.replace( np.nan , str_replace , inplace=True)

    # 결측치 행 삭제
    if need_drop :
        df_target.drop(df_tmp.index , inplace=True)

    return df_tmp

In [11]:
# EDA 기본정보 자동 분석 함수
def eda_info (df_param, need_category = False , category_count = 20) :

  df_target = df_param
  
  # df 변형이 필요한 경우 copy 
  if need_category :
    df_target = df_param.copy()
  
  list_columns = df_target.columns

  # 데이터셋 정보 확인
  #: 컬럼 자료형 , 전체 자료 갯수 , 컬럼 갯수 , 결측치 여부 , 전체 data 크기
  print_line()
  print ( "# 데이터셋 정보 확인" )
  print ( df_target.info() )


  # 컬럼 자료형 조회 (dtypes 이용) 
  #df_titanic.dtypes


  # 데이터의 행열 크기 조회
  print_line()
  print( "# 데이터의 행열 크기 = " , df_target.shape )


  # 결측치가 존재하는 컬럼명 조회
  print_line()
  """
  print( "# 컬럼별 결측치 갯수 ")
  print( df_target.isnull().sum() )

  print_line()
  print( "# 결측치 총 갯수 = " , df_target.isnull().sum().sum())
  """
  df_null = 결측치행열조회( df_target )
  print ( df_null.head(print_row_count) )


  # 컬럼별 중복값 확인
  print_line()
  print( "# 컬럼별 중복값 확인 ")
  for tmp_column in list_columns :
    # 중복값 갯수 조회
    tmp_dup_count = df_target[tmp_column].duplicated(keep = False).sum()
    
    if tmp_dup_count > 0 :
      print ( tmp_column , "컬럼에 중복값", tmp_dup_count , "개" )
      #print ( "index = " , df_target[tmp_column].duplicated(keep = False)   )
      #TODO : 중복값 인덱스 출력
    
  # 중복 데이터 확인
  print( "중복 data 갯수(전체)" , df_target.duplicated(keep = False).sum() )
  print( "중복 data " , df_target[df_target.duplicated(keep = False)].head(print_row_count) )


  # 각 컬럼별 값의 비율 조회
  # 컬럼명 조회
  print_line()
  print( "# 컬럼별 값의 비율 ")
  print ("컬럼 목록= " , list_columns)

  # 컬럼별 값의 비율 조회
  list_category_col_name = [] # 카테고리화 가능할 것으로 예상되는 컬럼명
  for tmp_column in list_columns :
    df_temp = df_target[tmp_column].value_counts(normalize=True ,dropna = True)
    
    print_line_s()
    print ( f"컬럼명 = {tmp_column} , 값의종류 갯수 = {len(df_temp)} " )
    
    if len(df_temp) <= category_count :
      list_category_col_name.append( tmp_column )
      print ( "Category 가능성 있음")
      print ( df_temp )
    #else :
      #print ( "값의 종류가 20개 이상임" )


  # 카테고리화 가능한 컬럼은 카테고리화 진행 
  if need_category :
    print ( "카테고리화 진행")
    for col_name in list_category_col_name :
      df_target[col_name] = df_target[col_name].astype('category')


  # 컬럼별 통계치 확인
  print_line()
  print ( "#컬럼별 통계특성 확인" )
  print ( df_target.describe())


  # 컬럼별 포함된 큭수문자 의 종류 조회
  print_line()
  print( "# 컬럼별 포함된 특수문자 종류 ")
  regx_특수문자제외한 = r'([^0-9a-zA-Z]+)'
  for tmp_column in list_columns :

    if df_target[tmp_column].dtype == 'object'  :
      print ( "컬럼명 = " , tmp_column )
      
      df_rslt = df_target[tmp_column].str.extractall( r'([^0-9a-zA-Z]+)'  )
      #display ( type(df_rslt) ) #=> DataFrame 

      set_rslt = []
      for idx in df_target.index :
        
        # TODO 값이 Nan인 경우의 정규표현식을 조사하지 않도록 한다,
        # 우선은 str인 경우만 
        tmp_val = df_target.loc[ idx , tmp_column]
        if isinstance( tmp_val , str) : 
          rslt = re.findall ( regx_특수문자제외한 , df_target.loc[ idx , tmp_column] )
          set_rslt += rslt 
        #else :
        #  display ( tmp_val )

      print( set(set_rslt) )
      
      print_line_s()


  # category 컬럼의 각 값 별 갯수와 비율 조회
  print_line()
  print ( "#category 타입 컬럼의 각 값 갯수와 비율 조회" )
  list_category_col_name = df_target.dtypes[df_target.dtypes.values == 'category'].index.tolist() 
  for col_name in list_category_col_name :
    sri_a = df_target[col_name].value_counts(dropna = True)
    sri_b = df_target[col_name].value_counts(normalize=True ,dropna = True)
    df_a = sri_a.to_frame( name = 'count')
    df_b = sri_b.to_frame( name = 'ratio')

    print (f"컬럼명 = {col_name} ")
    print ( df_a.join( df_b ) )
    print_line_s()

  #TODO 컬럼별 값 분포 그래프 표시
  #Boxplot과 Histogram을 통해서도 이상치 존재 여부를 확인해볼 수 있습니다.

  return df_target

In [12]:
# 숫자와 . 이외에 어떤 문자가 들어가 있는지 확인 하고 문제가 있는 Data를 df 형식으로 반환
# 
def 숫자이외의문자확인 (df_target , list_columns ) :
  list_err_idx = []
  regx_숫자를제외한 = r'([^0-9.]+)'
  for tmp_column in list_columns :

    if df_target[tmp_column].dtype == 'object'  :
      print ( "컬럼명 = " , tmp_column )
      
      df_rslt = df_target[tmp_column].str.extractall( regx_숫자를제외한  )
      #display ( type(df_rslt) ) #=> DataFrame 

      list_err_str = [] 
      for idx in df_target.index :
        tmp_val = df_target.loc[ idx , tmp_column]

        # TODO 값이 Nan인 경우의 정규표현식을 조사하지 않도록 하는 조건 추가
        # 우선은 str인 경우만 체크 진행 하도록 하였음
        if isinstance( tmp_val , str) : 

          rslt = re.findall ( regx_숫자를제외한 , df_target.loc[ idx , tmp_column] )
          if len(rslt) != 0 :
            list_err_str += rslt
            list_err_idx.append( idx )

        #else :
        #  display ( tmp_val )

      print( set(list_err_str) )
      
      print_line_s()

  err_idx = sorted( set(list_err_idx)) 

  # err 데이터 반환
  return df_target.loc[err_idx]

In [13]:
# DataFrame의 특정 컬럼의 data중에서 cond_sel 조건에 맞는 data를 fix_func 으로 수정 후 수정된 DataFrame을 반환
def fix_column_err_value ( df_temp_clean: pd.DataFrame , target_column: '수정할 column 명' 
                          , cond_sel:'수정 데이터 check 조건' 
                          , fix_func:'err를 수정할 함수' 
                          ) -> pd.DataFrame : #'수정된 DataFrame' 

    # err 조건에 해당하는 data 조회
    sri_err = df_temp_clean[ target_column ].apply( cond_sel )

    # 조회 결과 확인 
    display ( "수정전")
    display ( sri_err.sum() )
    display ( df_temp_clean.loc[ sri_err ].head(print_row_count) )


    # 오류를 수정 후 data 확인
    #(TODO) sri_fixed_col = df_temp_clean.loc[ sri_err ][[target_column]].apply( fix_func ,axis=1)
    sri_fixed_col = df_temp_clean.loc[ sri_err ][target_column].apply( fix_func )
    #display (sri_fixed_col.head(3))

    # 오류 수정한 데이터를 전처리 작업용 DataFrame에 반영
    df_temp_clean.loc[ sri_err, target_column ] = sri_fixed_col

    # 반영 결과 data 확인 
    display ( "반영결과")
    display ( df_temp_clean[sri_err].head(print_row_count))

    # # 반영 결과 집계 확인 
    # sri_err = df_temp_clean[ target_column ].apply( cond_sel )
    # display ( sri_err.sum() )

    return df_temp_clean

## 작업 DataFrame 지정

In [ ]:
# 데이터 로딩

# # 엑셀 파일 로딩
# df_001 = pd.read_excel("https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/stocks/Travel.xlsx", sheet_name = "008770 ")
# # CSV 파일 로딩
# df_red = pd.read_csv( "https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv" , sep = ",")
# df_white = pd.read_csv( "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv" , sep = ";")

# df_titanic = sns.load_dataset("titanic")

# df_patients = pd.read_csv('https://raw.githubusercontent.com/LamuneGitHub/A001_Python_Test/main/data/patients_info.csv')
# df_insuline_test = pd.read_csv('https://raw.githubusercontent.com/LamuneGitHub/A001_Python_Test/main/data/insuline_test.csv')

# df_final_revised = pd.read_csv('https://raw.githubusercontent.com/LamuneGitHub/A001_Python_Test/main/data/final_revised.csv')
# df_movie = pd.read_csv('https://raw.githubusercontent.com/LamuneGitHub/A001_Python_Test/main/data/movie.csv')

# df_discussion_114 = pd.read_csv('https://raw.githubusercontent.com/LamuneGitHub/A001_Python_Test/main/data/Discussion_114.csv')



# df_data = pd.read_csv('서울시_기간별_시간평균_대기환경_정보_2020.03.csv', encoding='euc-kr', usecols=['측정일시', '측정소명', '오존(ppm)'])

# read_csv 파라미터
"""    ,sep=','
    ,encoding='cp949' , encoding='euc-kr' , encoding='ISO-8859-1'
    , usecols=['측정일시', '측정소명', '오존(ppm)']
    , header=0 
    , index_col=0
"""

----
----
# # EDA 수행

In [ ]:
# Data 로드
df_tmp = pd.read_csv( "https://raw.githubusercontent.com/LamuneGitHub/AI15_Prj_01/main/vgames2.csv" , sep=","  , header=0  , index_col=0 ) 
df_target = df_tmp

In [7]:

target = 'vacc_h1n1_f'

train = pd.merge(pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/train.csv'), 
                 pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/vacc_flu/train_labels.csv')[target], left_index=True, right_index=True)


df_target = train

## 1. 시각적 EDA 수행

In [8]:

#맨위 
display( df_target.head(print_row_count) )
#마지막
display( df_target.tail(print_row_count) )
#무작위
display( df_target.sample(print_row_count) )

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,agegrp,education_comp,raceeth4_i,sex_i,inc_pov,marital,rent_own_r,employment_status,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 - 17 Years,NaN,3,1,2,NaN,2.0,NaN,4,"MSA, Not Principle City",2.0,3.0,5.0,NaN,NaN,9,CALIFORNIA,0
1,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,Very Effective,Very Low,Not Very Worried,Very Effective,Somewhat Low,Not At All Worried,45 - 54 Years,3.0,3,1,2,2.0,1.0,Employed,2,"MSA, Principle City",1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,7,NEBRASKA,0
2,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,Somewhat Effective,Somewhat Low,Very Worried,Somewhat Effective,Somewhat Low,Very Worried,45 - 54 Years,3.0,3,1,2,2.0,2.0,Employed,1,"MSA, Not Principle City",1.0,2.0,3.0,Transportation and Warehousing Industries,Transportation and Material Moving Occupations,1,MASSACHUSETTS,0

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,agegrp,education_comp,raceeth4_i,sex_i,inc_pov,marital,rent_own_r,employment_status,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
42151,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Somewhat Effective,Somewhat Low,Not At All Worried,Somewhat Effective,Somewhat High,Not At All Worried,18 - 34 Years,3.0,3,2,3,2.0,2.0,Employed,3,"MSA, Principle City",2.0,3.0,5.0,Retail Trade Industries,Office and Administrative Support Occupations,4,TENNESSEE,0
42152,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,0.0,0.0,NaN,1.0,Somewhat Effective,Somewhat High,Not At All Worried,Very Effective,Somewhat High,Not At All Worried,45 - 54 Years,4.0,3,2,1,1.0,1.0,Employed,3,Non-MSA,2.0,0.0,2.0,Health Care and Social Assistance Industries,Healthcare Practitioners and Technical Occupat...,4,GEORGIA,0
42153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6 Months - 9 Years,NaN,3,2,1,NaN,1.0,NaN,2,"MSA, Not Principle City",2.0,1.0,3.0,NaN,NaN,5,WISCONSIN,0

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,agegrp,education_comp,raceeth4_i,sex_i,inc_pov,marital,rent_own_r,employment_status,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
37554,2.0,2.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN,0.0,Somewhat Effective,Somewhat Low,Not Very Worried,Very Effective,Somewhat Low,Not Very Worried,55 - 64 Years,3.0,1,1,2,1.0,1.0,Unemployed,4,Non-MSA,3.0,0.0,3.0,NaN,NaN,10,OREGON,1
882,3.0,2.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN,0.0,NaN,0.0,Very Effective,Very High,Not At All Worried,Very Effective,Very High,Not At All Worried,55 - 64 Years,3.0,4,1,2,2.0,1.0,Not in Labor Force,4,Non-MSA,1.0,0.0,1.0,NaN,NaN,9,HAWAII,0
36510,2.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Somewhat Effective,Somewhat Low,Not Very Worried,Somewhat Effective,Somewhat Low,Somewhat Worried,35 - 44 Years,3.0,3,1,1,1.0,1.0,Employed,2,"MSA, Not Principle City",2.0,3.0,5.0,Manufacturing Industries,Production Occupations,8,SOUTH DAKOTA,0

----

## 2. 프로그램적 EDA 진행 기록

## 2.1 프로그램을 사용하여 데이터 특성 분석

In [ ]:
# 데이터 자동확인 리포트 함수 수행 
#
# 자동 카테고리화 진행
df_target = eda_info (df_target, need_category= True , category_count = 50) 
print( df_target.info() ) # 자동 카테고리화 이후의 결과 확인
display( df_target.head(print_row_count) ) # 자동 카테고리화 이후의 결과 확인

In [14]:
# 데이터 자동확인 리포트 함수 수행 
#
# 자동 카테고리화 진행
df_target = eda_info (df_target, need_category= False , category_count = 50) 
print( df_target.info() ) # 자동 카테고리화 이후의 결과 확인
display( df_target.head(print_row_count) ) # 자동 카테고리화 이후의 결과 확인

------------------------------------------------
# 데이터셋 정보 확인
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42154 entries, 0 to 42153
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   h1n1_concern                 33734 non-null  float64
 1   h1n1_knowledge               33734 non-null  float64
 2   behavioral_antiviral_meds    33635 non-null  float64
 3   behavioral_avoidance         33482 non-null  float64
 4   behavioral_face_mask         33710 non-null  float64
 5   behavioral_wash_hands        33683 non-null  float64
 6   behavioral_large_gatherings  33640 non-null  float64
 7   behavioral_outside_home      33633 non-null  float64
 8   behavioral_touch_face        33571 non-null  float64
 9   doctor_recc_h1n1             40269 non-null  float64
 10  doctor_recc_seasonal         40269 non-null  float64
 11  chronic_med_condition        40837 non-null  float64
 12  child_under_6_months         32705 non-null  float64
 13  health_insurance             22733 non-null  float64
 14  health_worker                32724 non-null  float64
 15  opinion_h1n1_vacc_effective  33375 non-null  object
 16  opinion_h1n1_risk            33329 non-null  object
 17  opinion_h1n1_sick_from_vacc  33285 non-null  object
 18  opinion_seas_vacc_effective  33220 non-null  object
 19  opinion_seas_risk            33153 non-null  object
 20  opinion_seas_sick_from_vacc  33089 non-null  object
 21  agegrp                       42154 non-null  object
 22  education_comp               31988 non-null  float64
 23  raceeth4_i                   42154 non-null  int64
 24  sex_i                        42154 non-null  int64
 25  inc_pov                      42154 non-null  int64
 26  marital                      31955 non-null  float64
 27  rent_own_r                   39958 non-null  float64
 28  employment_status            31876 non-null  object
 29  census_region                42154 non-null  int64
 30  census_msa                   42154 non-null  object
 31  n_adult_r                    41845 non-null  float64
 32  household_children           41845 non-null  float64
 33  n_people_r                   42020 non-null  float64
 34  employment_industry          17165 non-null  object
 35  employment_occupation        17165 non-null  object
 36  hhs_region                   42154 non-null  int64
 37  state                        42154 non-null  object
 38  vacc_h1n1_f                  42154 non-null  int64
dtypes: float64(21), int64(6), object(12)
memory usage: 12.5+ MB
None

------------------------------------------------
# 데이터의 행열 크기 =  (42154, 39)

------------------------------------------------
결측치가 포함된 Data 갯수 32833 / 42154
각 컬럼별 결측치 갯수
h1n1_concern                    8420
h1n1_knowledge                  8420
behavioral_antiviral_meds       8519
behavioral_avoidance            8672
behavioral_face_mask            8444
behavioral_wash_hands           8471
behavioral_large_gatherings     8514
behavioral_outside_home         8521
behavioral_touch_face           8583
doctor_recc_h1n1                1885
doctor_recc_seasonal            1885
chronic_med_condition           1317
child_under_6_months            9449
health_insurance               19421
health_worker                   9430
opinion_h1n1_vacc_effective     8779
opinion_h1n1_risk               8825
opinion_h1n1_sick_from_vacc     8869
opinion_seas_vacc_effective     8934
opinion_seas_risk               9001
opinion_seas_sick_from_vacc     9065
education_comp                 10166
marital                        10199
rent_own_r                      2196
employment_status              10278
n_adult_r                        309
household_children               309
n_people_r                       134
employment_industry            24989
employment_occupation          24989
dtype: int64
   h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0           NaN             NaN                        NaN
1           3.0             1.0                        0.0
2           2.0             1.0                        0.0

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   NaN                   NaN                    NaN
1                   0.0                   0.0                    1.0
2                   1.0                   0.0                    1.0

   behavioral_large_gatherings  behavioral_outside_home  \
0                          NaN                      NaN
1                          0.0                      0.0
2                          1.0                      0.0

   behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
0                    NaN               0.0                   0.0
1                    1.0               0.0                   0.0
2                    1.0               0.0                   1.0

   chronic_med_condition  child_under_6_months  health_insurance  \
0                    0.0                   NaN               1.0
1                    0.0                   0.0               NaN
2                    0.0                   0.0               NaN

   health_worker opinion_h1n1_vacc_effective opinion_h1n1_risk  \
0            NaN                         NaN               NaN
1            0.0              Very Effective          Very Low
2            0.0          Somewhat Effective      Somewhat Low

  opinion_h1n1_sick_from_vacc opinion_seas_vacc_effective opinion_seas_risk  \
0                         NaN                         NaN               NaN
1            Not Very Worried              Very Effective      Somewhat Low
2                Very Worried          Somewhat Effective      Somewhat Low

  opinion_seas_sick_from_vacc  education_comp  marital  rent_own_r  \
0                         NaN             NaN      NaN         2.0
1          Not At All Worried             3.0      2.0         1.0
2                Very Worried             3.0      2.0         2.0

  employment_status  n_adult_r  household_children  n_people_r  \
0               NaN        2.0                 3.0         5.0
1          Employed        1.0                 0.0         1.0
2          Employed        1.0                 2.0         3.0

                          employment_industry  \
0                                         NaN
1  Accommodation and Food Services Industries
2   Transportation and Warehousing Industries

                              employment_occupation
0                                               NaN
1  Food Preparation and Serving Related Occupations
2    Transportation and Material Moving Occupations

------------------------------------------------
# 컬럼별 중복값 확인
h1n1_concern 컬럼에 중복값 42154 개
h1n1_knowledge 컬럼에 중복값 42154 개
behavioral_antiviral_meds 컬럼에 중복값 42154 개
behavioral_avoidance 컬럼에 중복값 42154 개
behavioral_face_mask 컬럼에 중복값 42154 개
behavioral_wash_hands 컬럼에 중복값 42154 개
behavioral_large_gatherings 컬럼에 중복값 42154 개
behavioral_outside_home 컬럼에 중복값 42154 개
behavioral_touch_face 컬럼에 중복값 42154 개
doctor_recc_h1n1 컬럼에 중복값 42154 개
doctor_recc_seasonal 컬럼에 중복값 42154 개
chronic_med_condition 컬럼에 중복값 42154 개
child_under_6_months 컬럼에 중복값 42154 개
health_insurance 컬럼에 중복값 42154 개
health_worker 컬럼에 중복값 42154 개
opinion_h1n1_vacc_effective 컬럼에 중복값 42154 개
opinion_h1n1_risk 컬럼에 중복값 42154 개
opinion_h1n1_sick_from_vacc 컬럼에 중복값 42154 개
opinion_seas_vacc_effective 컬럼에 중복값 42154 개
opinion_seas_risk 컬럼에 중복값 42154 개
opinion_seas_sick_from_vacc 컬럼에 중복값 42154 개
agegrp 컬럼에 중복값 42154 개
education_comp 컬럼에 중복값 42154 개
raceeth4_i 컬럼에 중복값 42154 개
sex_i 컬럼에 중복값 42154 개
inc_pov 컬럼에 중복값 42154 개
marital 컬럼에 중복값 42154 개
rent_own_r 컬럼에 중복값 42154 개
employment_status 컬럼에 중복값 42154 개
census_region 컬럼에 중복값 42154 개
census_msa 컬럼에 중복값 42154 개
n_adult_r 컬럼에 중복값 42154 개
household_children 컬럼에 중복값 42154 개
n_people_r 컬럼에 중복값 42154 개
employment_industry 컬럼에 중복값 42154 개
employment_occupation 컬럼에 중복값 42154 개
hhs_region 컬럼에 중복값 42154 개
state 컬럼에 중복값 42154 개
vacc_h1n1_f 컬럼에 중복값 42154 개
중복 data 갯수(전체) 580
중복 data      h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
25           NaN             NaN                        NaN
27           NaN             NaN                        NaN
81           NaN             NaN                        NaN

    behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
25                   NaN                   NaN                    NaN
27                   NaN                   NaN                    NaN
81                   NaN                   NaN                    NaN

    behavioral_large_gatherings  behavioral_outside_home  \
25                          NaN                      NaN
27                          NaN                      NaN
81                          NaN                      NaN

    behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
25                    NaN               1.0                   1.0
27                    NaN               0.0                   0.0
81                    NaN               1.0                   1.0

    chronic_med_condition  child_under_6_months  health_insurance  \
25                    0.0                   NaN               1.0
27                    0.0                   NaN               1.0
81                    0.0                   NaN               1.0

    health_worker opinion_h1n1_vacc_effective opinion_h1n1_risk  \
25            NaN                         NaN               NaN
27            NaN                         NaN               NaN
81            NaN                         NaN               NaN

   opinion_h1n1_sick_from_vacc opinion_seas_vacc_effective opinion_seas_risk  \
25                         NaN                         NaN               NaN
27                         NaN                         NaN               NaN
81                         NaN                         NaN               NaN

   opinion_seas_sick_from_vacc              agegrp  education_comp  \
25                         NaN  6 Months - 9 Years             NaN
27                         NaN       10 - 17 Years             NaN
81                         NaN  6 Months - 9 Years             NaN

    raceeth4_i  sex_i  inc_pov  marital  rent_own_r employment_status  \
25           3      1        1      NaN         1.0               NaN
27           3      1        2      NaN         1.0               NaN
81           3      2        1      NaN         1.0               NaN

    census_region               census_msa  n_adult_r  household_children  \
25              1  MSA, Not Principle City        2.0                 2.0
27              2                  Non-MSA        2.0                 3.0
81              1  MSA, Not Principle City        2.0                 3.0

    n_people_r employment_industry employment_occupation  hhs_region  \
25         4.0                 NaN                   NaN           1
27         5.0                 NaN                   NaN           8
81         5.0                 NaN                   NaN           3

           state  vacc_h1n1_f
25  RHODE ISLAND            1
27  SOUTH DAKOTA            0
81  PENNSYLVANIA            1

------------------------------------------------
# 컬럼별 값의 비율
컬럼 목록=  Index(['h1n1_concern', 'h1n1_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_insurance',
       'health_worker', 'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
       'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'agegrp',
       'education_comp', 'raceeth4_i', 'sex_i', 'inc_pov', 'marital',
       'rent_own_r', 'employment_status', 'census_region', 'census_msa',
       'n_adult_r', 'household_children', 'n_people_r', 'employment_industry',
       'employment_occupation', 'hhs_region', 'state', 'vacc_h1n1_f'],
      dtype='object')

----------
컬럼명 = h1n1_concern , 값의종류 갯수 = 4
Category 가능성 있음
2.0    0.398441
1.0    0.305122
3.0    0.171667
0.0    0.124770
Name: h1n1_concern, dtype: float64

----------
컬럼명 = h1n1_knowledge , 값의종류 갯수 = 3
Category 가능성 있음
1.0    0.548705
2.0    0.355783
0.0    0.095512
Name: h1n1_knowledge, dtype: float64

----------
컬럼명 = behavioral_antiviral_meds , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.949309
1.0    0.050691
Name: behavioral_antiviral_meds, dtype: float64

----------
컬럼명 = behavioral_avoidance , 값의종류 갯수 = 2
Category 가능성 있음
1.0    0.727824
0.0    0.272176
Name: behavioral_avoidance, dtype: float64

----------
컬럼명 = behavioral_face_mask , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.932216
1.0    0.067784
Name: behavioral_face_mask, dtype: float64

----------
컬럼명 = behavioral_wash_hands , 값의종류 갯수 = 2
Category 가능성 있음
1.0    0.824333
0.0    0.175667
Name: behavioral_wash_hands, dtype: float64

----------
컬럼명 = behavioral_large_gatherings , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.644382
1.0    0.355618
Name: behavioral_large_gatherings, dtype: float64

----------
컬럼명 = behavioral_outside_home , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.661761
1.0    0.338239
Name: behavioral_outside_home, dtype: float64

----------
컬럼명 = behavioral_touch_face , 값의종류 갯수 = 2
Category 가능성 있음
1.0    0.67877
0.0    0.32123
Name: behavioral_touch_face, dtype: float64

----------
컬럼명 = doctor_recc_h1n1 , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.758276
1.0    0.241724
Name: doctor_recc_h1n1, dtype: float64

----------
컬럼명 = doctor_recc_seasonal , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.666567
1.0    0.333433
Name: doctor_recc_seasonal, dtype: float64

----------
컬럼명 = chronic_med_condition , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.750349
1.0    0.249651
Name: chronic_med_condition, dtype: float64

----------
컬럼명 = child_under_6_months , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.916007
1.0    0.083993
Name: child_under_6_months, dtype: float64

----------
컬럼명 = health_insurance , 값의종류 갯수 = 2
Category 가능성 있음
1.0    0.893063
0.0    0.106937
Name: health_insurance, dtype: float64

----------
컬럼명 = health_worker , 값의종류 갯수 = 2
Category 가능성 있음
0.0    0.888186
1.0    0.111814
Name: health_worker, dtype: float64

----------
컬럼명 = opinion_h1n1_vacc_effective , 값의종류 갯수 = 6
Category 가능성 있음
Somewhat Effective      0.441318
Very Effective          0.271221
Dont Know               0.180764
Not Very Effective      0.069273
Not At All Effective    0.033288
Refused                 0.004135
Name: opinion_h1n1_vacc_effective, dtype: float64

----------
컬럼명 = opinion_h1n1_risk , 값의종류 갯수 = 6
Category 가능성 있음
Somewhat Low     0.375649
Very Low         0.309970
Somewhat High    0.202976
Very High        0.064688
Dont Know        0.044436
Refused          0.002280
Name: opinion_h1n1_risk, dtype: float64

----------
컬럼명 = opinion_h1n1_sick_from_vacc , 값의종류 갯수 = 6
Category 가능성 있음
Not Very Worried      0.347965
Not At All Worried    0.338080
Somewhat Worried      0.224726
Very Worried          0.082409
Dont Know             0.005889
Refused               0.000931
Name: opinion_h1n1_sick_from_vacc, dtype: float64

----------
컬럼명 = opinion_seas_vacc_effective , 값의종류 갯수 = 6
Category 가능성 있음
Somewhat Effective      0.437778
Very Effective          0.380313
Not Very Effective      0.086394
Dont Know               0.047833
Not At All Effective    0.045515
Refused                 0.002167
Name: opinion_seas_vacc_effective, dtype: float64

----------
컬럼명 = opinion_seas_risk , 값의종류 갯수 = 6
Category 가능성 있음
Somewhat Low     0.343770
Somewhat High    0.288873
Very Low         0.227611
Very High        0.111664
Dont Know        0.026121
Refused          0.001961
Name: opinion_seas_risk, dtype: float64

----------
컬럼명 = opinion_seas_sick_from_vacc , 값의종류 갯수 = 6
Category 가능성 있음
Not At All Worried    0.445737
Not Very Worried      0.294207
Somewhat Worried      0.188280
Very Worried          0.067243
Dont Know             0.003657
Refused               0.000876
Name: opinion_seas_sick_from_vacc, dtype: float64

----------
컬럼명 = agegrp , 값의종류 갯수 = 7
Category 가능성 있음
65+ Years             0.202045
55 - 64 Years         0.166437
45 - 54 Years         0.157945
18 - 34 Years         0.156379
35 - 44 Years         0.117450
6 Months - 9 Years    0.102719
10 - 17 Years         0.097025
Name: agegrp, dtype: float64

----------
컬럼명 = education_comp , 값의종류 갯수 = 4
Category 가능성 있음
4.0    0.397149
3.0    0.280730
2.0    0.227523
1.0    0.094598
Name: education_comp, dtype: float64

----------
컬럼명 = raceeth4_i , 값의종류 갯수 = 4
Category 가능성 있음
3    0.776842
2    0.081629
1    0.076529
4    0.065000
Name: raceeth4_i, dtype: float64

----------
컬럼명 = sex_i , 값의종류 갯수 = 2
Category 가능성 있음
2    0.571832
1    0.428168
Name: sex_i, dtype: float64

----------
컬럼명 = inc_pov , 값의종류 갯수 = 4
Category 가능성 있음
2    0.462922
1    0.279428
4    0.154505
3    0.103146
Name: inc_pov, dtype: float64

----------
컬럼명 = marital , 값의종류 갯수 = 2
Category 가능성 있음
1.0    0.535941
2.0    0.464059
Name: marital, dtype: float64

----------
컬럼명 = rent_own_r , 값의종류 갯수 = 4
Category 가능성 있음
1.0     0.748786
2.0     0.233695
99.0    0.015917
77.0    0.001602
Name: rent_own_r, dtype: float64

----------
컬럼명 = employment_status , 값의종류 갯수 = 3
Category 가능성 있음
Employed              0.538744
Not in Labor Force    0.402183
Unemployed            0.059073
Name: employment_status, dtype: float64

----------
컬럼명 = census_region , 값의종류 갯수 = 4
Category 가능성 있음
3    0.347867
4    0.262988
2    0.221758
1    0.167386
Name: census_region, dtype: float64

----------
컬럼명 = census_msa , 값의종류 갯수 = 3
Category 가능성 있음
MSA, Not Principle City    0.449708
MSA, Principle City        0.286141
Non-MSA                    0.264150
Name: census_msa, dtype: float64

----------
컬럼명 = n_adult_r , 값의종류 갯수 = 4
Category 가능성 있음
2.0    0.573808
1.0    0.266531
3.0    0.115330
4.0    0.044330
Name: n_adult_r, dtype: float64

----------
컬럼명 = household_children , 값의종류 갯수 = 4
Category 가능성 있음
0.0    0.562815
1.0    0.176509
2.0    0.161381
3.0    0.099295
Name: household_children, dtype: float64

----------
컬럼명 = n_people_r , 값의종류 갯수 = 7
Category 가능성 있음
2.0    0.304450
1.0    0.212280
4.0    0.184484
3.0    0.172894
5.0    0.100571
6.0    0.019396
7.0    0.005926
Name: n_people_r, dtype: float64

----------
컬럼명 = employment_industry , 값의종류 갯수 = 23
Category 가능성 있음
Health Care and Social Assistance Industries                     0.179784
Education Services Industries                                    0.133877
Professional, Scientific, and Technical Services Industries      0.089426
Retail Trade Industries                                          0.079231
Construction Industries                                          0.064958
Public Administration Industries                                 0.064259
Manufacturing Industries                                         0.061870
Finance and Insurance Industries                                 0.045325
Other Services (except Public)                                   0.041771
Accommodation and Food Services Industries                       0.039149
Transportation and Warehousing Industries                        0.037110
Information Industries                                           0.024818
Administrative and Support and Waste Management                  0.024235
Agriculture, Forestry, Fishing, and Hunting Industries           0.021963
Arts, Entertainment, and Recreation Industries Administration    0.020565
Real Estate and Rental and Leasing Industries                    0.015846
Wholesale Trade Industries                                       0.015438
Armed Forces                                                     0.011302
Not ascertained                                                  0.010312
Utilities Industries                                             0.009613
Mining Industries                                                0.006350

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_insurance,health_worker,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,agegrp,education_comp,raceeth4_i,sex_i,inc_pov,marital,rent_own_r,employment_status,census_region,census_msa,n_adult_r,household_children,n_people_r,employment_industry,employment_occupation,hhs_region,state,vacc_h1n1_f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 - 17 Years,NaN,3,1,2,NaN,2.0,NaN,4,"MSA, Not Principle City",2.0,3.0,5.0,NaN,NaN,9,CALIFORNIA,0
1,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,Very Effective,Very Low,Not Very Worried,Very Effective,Somewhat Low,Not At All Worried,45 - 54 Years,3.0,3,1,2,2.0,1.0,Employed,2,"MSA, Principle City",1.0,0.0,1.0,Accommodation and Food Services Industries,Food Preparation and Serving Related Occupations,7,NEBRASKA,0
2,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,Somewhat Effective,Somewhat Low,Very Worried,Somewhat Effective,Somewhat Low,Very Worried,45 - 54 Years,3.0,3,1,2,2.0,2.0,Employed,1,"MSA, Not Principle City",1.0,2.0,3.0,Transportation and Warehousing Industries,Transportation and Material Moving Occupations,1,MASSACHUSETTS,0

## 2.2 데이터 정제
  
    반복 {
        2.2.1 문제점 리스팅
        2.2.2 문제점 해결
               & 결과 확인 
    }

In [ ]:
# 도출된 문제점 수정


#(v) 결측치 확인, 처리  -> 삭제 , 357 / 16598
df_null = 결측치행열조회(df_target, need_drop = True   )

#(v) Name 중복 컬럼 확인 -> OK
"""
df_target[df_target['Name'].duplicated(keep = False)]
df_target[df_target['Name'] == "Candace Kane's Candy Factory"]
"""

#(v) 중복값 삭제 -> 1개 삭제
df_target.drop_duplicates(inplace=True)

# Year 수정 별도로 좀 더 자세히 하는것으로 변경 하였음 ( 아래 확인 )
"""
#(v) Year 값이 0 인 이상치 수정. -> 3개 , 매출값도 크지 않음 -> 삭제
cond_tmp = df_target['Year'] == 0
len (df_target[cond_tmp])
df_target.drop(df_target[cond_tmp].index, inplace=True)
"""
#(v) Year -> int 로 수정
#(TODO) float 컬럼의 값이 모두 .0 형식(int) 형식인지 체크  
# int로 type변경
df_target['Year'] = df_target['Year'].astype( 'int')

#(v) Publisher 컬럼 필요 없으므로 Drop
#(v) Name 컬럼 필요 없으므로 Drop
df_target.drop( ['Publisher','Name' ] , axis='columns' , inplace=True)

# 데이터 재 확인
# df_target = eda_info (df_target)

In [ ]:
# # df 백업
# df_backup_copy = df_target.copy()

In [ ]:
# df 복원
#df_target = df_backup_copy.copy()

In [ ]:
#[v] Sales 컬럼에 들어있는 특수 문자 , 영문자 확인 및 삭제 , int로 변환

# 이름에 Sales 가 포함된 컬럼을 대상으로 함 
list_sales_col_name = [ col for col in df_target.columns if col.find("Sales") != -1  ]  
print  (list_sales_col_name )
list_columns = list_sales_col_name

# 컬럼에 숫자 이외의 문자가 있는지 여부 확인
숫자이외의문자확인 (df_target , list_columns );

In [ ]:
# K가 들어가 있는 컬럼은 * 1000 
# M이 들어가 있는 컬럼은 * 10000000  = 10^6
# K와 Md이 없는 컬럼은 M과 똑같이 * 1000000 = 10^6
#   해준후 int로 컬럼 data type을 변경한다.

# err 데이터 확인
#print( df_target.loc[err_idx] )

# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
cond_all = lambda x: True 
#cond_contain_M = lambda x: True if re.search( 'M' , x).group(0) else False 

# err 수정 function.
def fix_func( x ):
  fix_value = x
  try:

    if re.search( 'K' , x ) :
      fix_value = x.replace ( "K" , "" )
      fix_value = float(fix_value) * 10**3    
    elif re.search( 'M' , x ) :
      fix_value = x.replace ( "M" , "" )
      fix_value = float(fix_value) * 10**6
    else :
      fix_value = float(fix_value) * 10**6

    fix_value = int(fix_value)
    return fix_value
  except Exception:
    print( f"에러 발생 {x} , { type( x )} ")

# 수정 함수 호출
for target_column in list_columns :
  df_target = fix_column_err_value( df_target , target_column , cond_all, fix_func )

In [ ]:
a = 숫자이외의문자확인 (df_target , list_columns )

In [ ]:
# 데이터 클리닝 결과 재확인
df_target = eda_info (df_target)

In [ ]:
#(v) Year 최저 값이 이상한 것을 발견 하였음 
print( sorted(df_target.Year.unique()) )

In [ ]:
# Year 값 수정
"""Year 
    0~ 16  => 2000년도
    86~98 => 1900년도
"""

target_column = 'Year'

# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
cond_all = lambda x: True 

# err 수정 function.
def fix_func( x ):
  fix_value = x
  try:

    if x <= 16  :
      fix_value = x + 2000    
    elif x <= 98  :
      fix_value = x + 1900
    
    fix_value = int(fix_value)
    return fix_value
  except Exception:
    print( f"에러 발생 {x} , { type( x )} ")

# 수정 함수 호출
df_target = fix_column_err_value( df_target , target_column , cond_all, fix_func )

In [ ]:
# 데이터 클리닝 결과 재확인
df_target = eda_info (df_target)

----
데이터 클리닝 완료

----

## 3. Feature Engineering
: 수학적인 연산과 도메인 지식을 이용하여 raw data로부터 유용한 feature를 도출해 내는 과정

In [ ]:
# # df 백업
# df_backup_copy = df_target.copy()

In [ ]:
# df_target = df_backup_copy.copy()

In [ ]:
df_target.head(5)

In [ ]:
# 플렛폼을 모바일 , 콘솔 , 컴퓨터의 대분류로도 구분
import sys 

lst_portable = [ 'DS', '3DS', 'PSP', 'GB', 'GBA', 'PSV', 'WS', 'GG', 'WiiU']
lst_pc = ['PC']
list_all = df_target.Platform.unique().tolist()
lst_console = [ x for x in list_all if (x not in lst_portable) & (x not in lst_pc) ]
print ( lst_console) # ['Wii', 'PS3', 'PS', 'PS4', 'PS2', 'XB', 'X360', 'GC', '2600', 'SAT', 'NES', 'DC', 'N64', 'XOne', 'SNES', 'GEN', 'SCD', 'NG', 'TG16', '3DO', 'PCFX']


target_column = 'Platform'

# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
cond_SCD = lambda x: True if x == 'SCD' else False 
cond_all = lambda x: True

# 수정 function.
def fix_func( x ):
  
  ret_value = "-"

  try:
    
    if x['Platform'] in lst_portable  :
      ret_value = 'portable'
    elif x['Platform'] in lst_console  :
      ret_value = 'console'
    elif x['Platform'] in lst_pc  :
      ret_value = 'pc'
    
    df_target.loc[x.name,"Type"] = ret_value
   
    return x.str
  except Exception:
    print( f"에러 발생 data = {x} , type = { type( x )} , idx = {x.name} ")
    sys.exit()



######

# err 조건에 해당하는 data 조회
sri_err = df_target[ target_column ].apply( cond_all )

sri_fixed_col = df_target.loc[ sri_err ][[target_column]].apply( fix_func ,axis=1  )
df_target.loc[sri_err].head(5)

In [ ]:
# 데이터 클리닝 결과 재확인
df_target = eda_info (df_target, need_category = True , category_count = 50 )

### 클리닝 된 데이터를 파일로 저장

In [ ]:
df_target.to_csv('vgames2_after_cleaning_01.csv', index=False)

----
----
# 4. 분석

## 목표 ( 최종 )

**요청사항 : 다음 분기에 어떤 게임을 설계해야 할까?**

    최종 목표 요청사항 상세 정의 
    - 1 단계 
        * 어떤 장르를 개발해야 하는가?
        * 어떤 플렛폼용으로 개발해야 하는가?
        * 어느지역 ( 언어지원 ,  주요 마켓팅 역량 집중 )을 주요 타겟으로 잡아야 하는가?

    - 2 단계 
        * 어떤 장르를 개발해야 하는가?
            -> 어떤 장르의 게임을 개발했을 때 히트 게임이 될 확률이 높은가?
            -> p( Hit 게임 | 장르 ) 
        * 어떤 플렛폼용으로 개발해야 하는가?
            -> 어떤 플렛폼 의 게임을 개발했을 때 히트 게임이 될 확률이 높은가?
            -> p( Hit 게임 | 플렛폼 ) 

        * 어느지역 ( 언어지원 ,  주요 마켓팅 역량 집중 )을 주요 타겟으로 잡아야 하는가?
            -> 어떤 지역을 지원하는 게임을 개발했을 때 히트 게임이 될 확률이 높은가?
            -> p( Hit 게임 | 지역 )

    - 3 단계 
        목표 -> 각 장르별로 매출이 높을 확률 ? 베이지안 
            A : hit 게임
            B : 장르(각)

            P(A|B) = P(B|A) * P(A) / P(B)

        목표 -> 각 플렛폼 별로 매출이 높을 확률  ? 베이지안
            A : hit 게임
            B : 플렛폼(각)

            P(A|B) = P(B|A) * P(A) / P(B)

        목표 -> 각 지역별로 언어지원,집중 마켓팅을 했을때 매출이 높을 확률  ? 베이지안
            A : hit 게임
            B : 지역(각)

            P(A|B) = P(B|A) * P(A) / P(B)

----
----
# 시각화

### 한글 폰트 설치
: 설치 후 메뉴>런타임>런타임 다시 시작 할 것

In [ ]:
# 한글 폰트 설치 
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

In [ ]:
# 폰트 셋팅
plt.style.use('ggplot')
font = {'size': 12,
        'family': 'NanumBarunGothic'}
mpl.rc('font', **font)

----

In [ ]:
# 생존여부, 성별 별 평균요금 df 조회
df_temp = df_titanic.groupby( ['survived' ,'sex'] ).mean()
df_temp

In [ ]:
df_temp

In [ ]:
df_red['color'] = np.repeat('red', len(df_red))
df_white['color'] = np.repeat('white', len(df_white))
df_temp = df_red.append(df_white)

df_temp.groupby('color')['quality'].mean().plot(kind='bar', 
                                                title='Average Wine Quality by Color', 
                                                fontsize=13, 
                                                color=['red', 'blue'], 
                                                alpha=0.4);

In [ ]:
counts = df_temp.groupby(['quality', 'color']).count()['pH']
counts.plot(kind='bar', color=['red','blue'], title='Counts by Wine Quality and Color', fontsize=15, alpha=0.4);

In [ ]:
df_temp = df_titanic

# 막대그래프 표시 
df_temp.plot(kind = 'bar')

In [ ]:
df_temp = df_titanic

temp = df_temp.groupby(['sex', 'survived'])['fare'].mean().reset_index()
fig, ax = plt.subplots(figsize=(8, 6))
sns.barplot(data=temp, x='survived', y='fare', hue='sex', ax=ax)
ax.set_title("생존 여부와 성별에 따른 평균 요금")
ax.set_xticklabels(['Not Survived', 'Survived'])
plt.show();

In [ ]:
df_temp = df_titanic

fig, ax = plt.subplots(figsize=(8, 8))
fig = plt.pie(df_temp['survived'].value_counts(), labels=['No', 'Yes'], autopct='%.2f%%',
              textprops={'fontsize':14})
plt.title('Survived', fontsize=16)
plt.show()

In [ ]:
df_temp = df_titanic

fig, ax = plt.subplots(figsize=(8, 6))
sns.countplot(x=df_temp['pclass'].values, ax=ax)
plt.title('클래스별 수', fontsize=16)
plt.show()

In [ ]:
sns.countplot(x=df_temp['pclass'].values)

In [ ]:
df_temp['age'].plot(kind='hist', bins=8)

In [ ]:
df_temp = df_titanic

bins = np.arange(0, df_temp.age.max()+df_temp.age.max()/8, df_temp.age.max()/8)
fig, ax = plt.subplots(figsize=(8, 6))
fig = plt.hist(x=df_temp['age'], bins=bins)
plt.title('나이 분포', fontsize=16)
plt.xlabel('나이')
plt.ylabel('수')
plt.show()

In [ ]:
df_temp = df_red

# quality 에 따른 휘발성산의 차이를 scatter plot 으로 확인
plt.scatter(df_temp['quality'], df_temp['volatile acidity'])

In [ ]:
df_temp = df_red

# quality 에 따른 평균 휘발성산 확인
group_volatile_acidity = df_temp['volatile acidity'].groupby(df_temp['quality'])
print(group_volatile_acidity.mean())

# plot으로 시각화
plt.plot(group_volatile_acidity.mean());

----
# # Data Wrangling (데이터 정제) , Data Preprocessing (데이터 전처리)  
  : 실제 작업의 70~80%가 소요 된다고 함 

  * 데이터 품질
    * 결측값 처리
    * 잘못된 값 처리
  * 구조적 품질
    * 정규화

In [ ]:
# DataFrame 복사
df_patients_clean = df_patients.copy()

### Missing value (결측값)

특정 컬럼의 결측값 갯수 확인

In [ ]:
# 환자 데이터 중 키, 몸무게, 체질량지수 컬럼의 결측값 확인
df_patients_error_tmp = df_patients[df_patients['키'].isnull() | df_patients['몸무게'].isnull() | df_patients['체질량지수'].isnull()]
df_patients_error_tmp.head(3)

(TODO) 특정 컬럼의 결측값을 수정

### Outliers (잘못된 값,이상치)  수정

In [ ]:
# 전처리 작업용 임시 DataFrame 생성
df_temp_clean = df_final_revised.copy()

* URL 주소 
  : https:// 로 시작 하지 않는 데이터의 앞에 https://를 붙인다.

In [ ]:
# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
target_column = 'Poster_Link'
cond_err = lambda x: True if not x.startswith('https://') else False
fix_func = lambda x: 'https://' + x

# 수정 함수 호출
df_result = fix_column_err_value( df_temp_clean , target_column , cond_err, fix_func )

다른 열의 값을 가지고 와서 합치기

In [ ]:
# 전처리 작업용 임시 DataFrame 생성
df_temp_clean = df_final_revised.copy()

# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
target_column = 'Series_Title'
cond_err = lambda x: True 

# case 01 
fix_func = lambda x: df_temp_clean.loc[x.name,"Runtime"] + df_temp_clean.loc[x.name,"Genre"]

# case 02 : 조건 체크 columm 과 변경 column이 다른 경우
def fix_func2 ( x ) :
  df_temp_clean.loc[x.name,"Certificate"] = df_temp_clean.loc[x.name,"Runtime"] + df_temp_clean.loc[x.name,"Genre"]
  return df_temp_clean.loc[x.name,target_column]

df_result = fix_column_err_value( df_temp_clean , target_column , cond_err, fix_func2 )

특정 컬럼을 필요 없는 문자 삭제 후 int로 타입 변경

In [ ]:
# case 01

# 전처리 작업용 임시 DataFrame 생성
df_temp_clean = df_final_revised.copy()

df_temp_clean['Runtime'] = df_temp_clean['Runtime'].str.extract('([0-9]+)').astype('int16')
# movie['Runtime'] = movie['Runtime'].str.split().str[0].astype('int16')

In [ ]:
# case 02

# 전처리 작업용 임시 DataFrame 생성
df_temp_clean = df_final_revised.copy()


# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
target_column = 'Runtime'
cond_sel = lambda x: True
fix_func = lambda x: re.search( r'([0-9]+)' , x).group(0)

# 처리할 값에 대한 예외 처리가 필요한 경우 조건 처리를 포함한 function을 사용하여야 한다. 
def fix_func2( input ):
    if not bool( input ) : 
      return np.nan
    if not isinstance( input ,str ) :
      print( type(input)  ,  input)
      return np.nan
    return re.search( r'([0-9]+)' , input ).group(0)

# 수정 함수 호출
df_result = fix_column_err_value( df_temp_clean , target_column , cond_sel, fix_func ) 
df_result.head()

# Lecture 에서 따온 특수문자 체크 코드

In [ ]:
reg_con_01 = r'[_,!,.,@#$%()^\d+]'

# 특수 문자가 포함되었는지 여부 체크
def has_errors(inputString):
  return bool(re.search( reg_con_01 , inputString))


# 이름에 섞여 있는 오류 데이터를 확인
error_condition = df_patients_clean.이름.apply(has_errors)
error_names = df_patients_clean[error_condition]
print(error_names)

print("-------------")
# 코드가 정확하게 오류들을 제거하는지 확인 
error_names.이름 = df_patients_clean.이름.str.replace(reg_con_01, '')
print(error_names)

print("-------------")
# 반영
df_patients_clean.이름 = df_patients_clean.이름.str.replace(reg_con_01, '')

# 반영결과 확인
df_patients_clean[error_condition]

### 이메일 형식 체크

In [ ]:
df_discussion_114.head(20)

In [ ]:
regx_이메일 = r'[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}'
regx_핸드폰 = r'\d{3}-\d{3,4}-\d{4}'

# 작업 DataFrame 지정
df_temp_clean = df_discussion_114.copy()

# 오류 검사 조건, 수정 함수, 대상 컬럼 명 
target_column = 'email'

#cond_sel = lambda x: False if re.search( regx_이메일 , x).group(0) else True
def cond_sel (x) :
  if isinstance ( x , str ) :
   if re.match( regx_이메일 , x) :
    return False
   else :
    return True
  else :
    # str이 아닌 경우= Nan 인 경우 , 수정 대상으로 체크
    return True

def fix_func(x) :
  # 수정 대상인 경우 (TODO) 알맞은 코딩을 해주어야 함
  return "(TODO) Fix"


# 수정 함수 호출
df_result = fix_column_err_value( df_temp_clean , target_column , cond_sel, fix_func ) 

# 수정 결과 확인
display(df_result.head(11))
display(df_result.tail(5))

### (TODO) 전화번호 형식 체크

### 컬럼의 분리

In [ ]:
# 환자나이 컬럼 분리
# 나이 컬럼에서 숫자만 뽑아내어 int로 변환 후 환자나이 컬럼을 생성 
df_patients_clean['환자나이'] = df_patients_clean.나이.str.extract('(\d+)').astype('int') 

# 성별 컬럼 분리
# 나이 컬럼에서 숫자를 모두 제거 후 성별 컬럼을 생성
df_patients_clean['성별'] = df_patients_clean.나이.str.replace(r'[^a-zA-Z]', '', regex=True) #숫자만 삭제 한다.

# 기존 나이 컬럼 제거
patients_clean = df_patients_clean.drop('나이', axis='columns' )

In [ ]:
# 성별을 category 데이터 타입으로 변화 , 영어를 한글로 변환
patients_clean.성별 = patients_clean.성별.replace({'male':'남', 'female':'여'})
patients_clean.성별 = patients_clean.성별.astype('category')

## 구조적 문제 수정  ( df 합치기)
df1.melt(id_vars='index', value_vars=['A', 'B'])

pd.melt(df1, id_vars = 'index', var_name='variable', value_name='value')

# 결과 데이터를 파일로 저장

# 결측치

In [ ]:
# 컬럼별 결측치 조회
print( df.isnull().sum() )

In [ ]:
# 특정열 기준 결측치 삭제 
df.dropna(subset=['Math'])

In [ ]:
# 결측치를 평균 모두 채워주기 
X_train.fillna(X_train.mean(), inplace=True)
X_test.fillna(X_test.mean(), inplace=True)

In [ ]:
# 컬럼별 결측치% 를 확인
df.isna().sum()[df.isna().sum() !=0]/len(df)

# 결측치가 80%가 넘는 컬럼도 삭제해주겠습니다.
cols = ['Alley', 'PoolQC', 'Fence', 'MiscFeature']
df.drop(cols, axis=1, inplace=True)

# 기타

In [ ]:
# 고유한 값이 너무 많은 컬럼도 예측에 도움이 되지 않으니 확인하고 삭제해주겠습니다. 
df.nunique()[df.nunique()/len(df)>0.7]
cols = ['Id', 'LotArea']
df.drop(cols, axis=1, inplace=True)

# 시각화

In [ ]:
# 시각화  ( 2*3 )


# 범주형 컬럼과 타겟과의 관계
fig = plt.figure()
fig.set_size_inches(24, 12)
(ax1, ax2, ax3), (ax4, ax5, ax6) = fig.subplots(nrows=2, ncols=3)
sns.boxplot(data=df, x='OverallQual', y='SalePrice', ax=ax1)
ax1.set_title('SalePrice - OverallQual')
sns.boxplot(data=df, x='GarageCars', y='SalePrice', ax=ax2)
ax2.set_title('SalePrice - GarageCars')
sns.boxplot(data=df, x='FullBath', y='SalePrice', ax=ax3)
ax3.set_title('SalePrice - FullBath')

# 수치형 컬럼과 타겟과의 관계
sns.scatterplot(data=df, x='GrLivArea', y='SalePrice', ax=ax4)
ax4.set_title('SalePrice - OverallQual')
sns.scatterplot(data=df, x='GarageArea', y='SalePrice', ax=ax5)
ax5.set_title('SalePrice - GarageArea')
sns.scatterplot(data=df, x='TotalBsmtSF', y='SalePrice', ax=ax6)
ax6.set_title('SalePrice - TotalBsmtSF')

plt.show()

# Drop

In [ ]:
# 컬럼 drop
df_clean = df.drop('id', axis='columns' )

# 컬럼 변경

In [ ]:
#  문자 -> 숫자
genh_encoding = {'Poor':1, 'Fair':2, 'Excellent':3, 'Good':4, 'Very good':5}

df['GenHealth'] = df['GenHealth'].replace(genh_encoding)
df['GenHealth'].astype('float')

# 4분위에 따른 이상치 삭제

In [ ]:
# 수치형 특성의 아웃라이어를 삭제해주겠습니다.

def outlier_iqr(data) :
    q1, q3 = data.quantile([0.25, 0.75])
    iqr = q3 - q1
    return q3 + (iqr*1.5)

bmi_upper = outlier_iqr(df['BMI'])
ph_upper = outlier_iqr(df['PhysicalHealth'])
mh_upper = outlier_iqr(df['MentalHealth'])
sl_upper = outlier_iqr(df['SleepTime'])

df = df[(df['BMI']<bmi_upper) | (df['PhysicalHealth']<ph_upper) | (df['MentalHealth']<mh_upper) | (df['SleepTime'] <sl_upper)]

# 중복값 삭제

# 중복값을 확인해보겠습니다.
# 약 5% 정도의 데이터가 중복되어있는 것을 확인할 수 있습니다. 중복 데이터는 삭제해주겠습니다.
print("중복된 데이터의 비율", df.duplicated().sum()/len(df))
df.drop_duplicates(keep='first', inplace=True)
df.shape

# 타겟 범주 비율 확인

In [ ]:
# 타겟 데이터 범주의 비율을 확인합니다.
y =  df['HeartDisease']
print("타겟데이터의 비율\n",y.value_counts(normalize=True))

%matplotlib inline
sns.countplot(x=y);